/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountSettingsAccount: typeof import('./src/components/pages/account-settings/AccountSettingsAccount.vue')['default']
    AccountSettingsNotification: typeof import('./src/components/pages/account-settings/AccountSettingsNotification.vue')['default']
    AccountSettingsSecurity: typeof import('./src/components/pages/account-settings/AccountSettingsSecurity.vue')['default']
    AnalyticsAward: typeof import('./src/components/dashboard/AnalyticsAward.vue')['default']
    AnalyticsBarCharts: typeof import('./src/components/dashboard/AnalyticsBarCharts.vue')['default']
    AnalyticsDepositWithdraw: typeof import('./src/components/dashboard/AnalyticsDepositWithdraw.vue')['default']
    AnalyticsSalesByCountries: typeof import('./src/components/dashboard/AnalyticsSalesByCountries.vue')['default']
    AnalyticsTotalEarning: typeof import('./src/components/dashboard/AnalyticsTotalEarning.vue')['default']
    AnalyticsTotalProfitLineCharts: typeof import('./src/components/dashboard/AnalyticsTotalProfitLineCharts.vue')['default']
    AnalyticsTransactions: typeof import('./src/components/dashboard/AnalyticsTransactions.vue')['default']
    AnalyticsUserTable: typeof import('./src/components/dashboard/AnalyticsUserTable.vue')['default']
    AnalyticsWeeklyOverview: typeof import('./src/components/dashboard/AnalyticsWeeklyOverview.vue')['default']
    AuthProvider: typeof import('./src/components/pages/authentication/AuthProvider.vue')['default']
    CardBasic: typeof import('./src/components/pages/cards/card-basic/CardBasic.vue')['default']
    CardNavigation: typeof import('./src/components/pages/cards/card-basic/CardNavigation.vue')['default']
    CardSolid: typeof import('./src/components/pages/cards/card-basic/CardSolid.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    DemoFormLayoutHorizontalForm: typeof import('./src/components/pages/form-layouts/DemoFormLayoutHorizontalForm.vue')['default']
    DemoFormLayoutHorizontalFormWithIcons: typeof import('./src/components/pages/form-layouts/DemoFormLayoutHorizontalFormWithIcons.vue')['default']
    DemoFormLayoutMultipleColumn: typeof import('./src/components/pages/form-layouts/DemoFormLayoutMultipleColumn.vue')['default']
    DemoFormLayoutVerticalForm: typeof import('./src/components/pages/form-layouts/DemoFormLayoutVerticalForm.vue')['default']
    DemoFormLayoutVerticalFormWithIcons: typeof import('./src/components/pages/form-layouts/DemoFormLayoutVerticalFormWithIcons.vue')['default']
    DemoSimpleTableBasics: typeof import('./src/components/pages/tables/DemoSimpleTableBasics.vue')['default']
    DemoSimpleTableDensity: typeof import('./src/components/pages/tables/DemoSimpleTableDensity.vue')['default']
    DemoSimpleTableFixedHeader: typeof import('./src/components/pages/tables/DemoSimpleTableFixedHeader.vue')['default']
    DemoSimpleTableHeight: typeof import('./src/components/pages/tables/DemoSimpleTableHeight.vue')['default']
    DemoSimpleTableTheme: typeof import('./src/components/pages/tables/DemoSimpleTableTheme.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    FormLayoutHorizontalForm: typeof import('./src/components/user-interface/form-layouts/FormLayoutHorizontalForm.vue')['default']
    FormLayoutHorizontalFormWithIcons: typeof import('./src/components/user-interface/form-layouts/FormLayoutHorizontalFormWithIcons.vue')['default']
    FormLayoutMultipleColumn: typeof import('./src/components/user-interface/form-layouts/FormLayoutMultipleColumn.vue')['default']
    FormLayoutVerticalForm: typeof import('./src/components/user-interface/form-layouts/FormLayoutVerticalForm.vue')['default']
    FormLayoutVerticalFormWithIcons: typeof import('./src/components/user-interface/form-layouts/FormLayoutVerticalFormWithIcons.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableBasic: typeof import('./src/components/user-interface/tables/TableBasic.vue')['default']
    TableDark: typeof import('./src/components/user-interface/tables/TableDark.vue')['default']
    TableDensity: typeof import('./src/components/user-interface/tables/TableDensity.vue')['default']
    TableFixedHeader: typeof import('./src/components/user-interface/tables/TableFixedHeader.vue')['default']
    TableHeight: typeof import('./src/components/user-interface/tables/TableHeight.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    TypographyHeadlines: typeof import('./src/components/user-interface/typography/TypographyHeadlines.vue')['default']
    TypographyTexts: typeof import('./src/components/user-interface/typography/TypographyTexts.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
